# Site settings
title: "Brent Robbins"
description: ""
baseurl: "https://brentrobbins.net" # the subpath of your site, e.g. /blog/ - keep empty!
url: "" # the base hostname & protocol for your site - don't include the forward slash
version: "3.7.1" # the version of jekyll
#site_id: "22551"

#CloudCannon defaults
uploads_dir: "assets/images"

# Gems for plugins
plugins:
  - jekyll-paginate-v2 # Needed to add paginate on Jekyll ver 3+
  - jekyll-sitemap # Simple jekyll plugin that creates a sitemap.xml file and you can exclude files by adding 'sitemap:false' to the frontmatter of any file(s).
  - jekyll-include-cache # Cache jekyll includes to improve build times

# Permalinks
permalink: pretty

# Compress HTML
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: true
  startings: [html, head, body]

# Pagination V2 Settings: https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  enabled: false
  per_page: 4
  #permalink: '/news/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'title'
  #sort_reverse: false
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true
  # The default document collection to paginate if nothing is specified ('news' is default)
  collection: 'posts'

#Collections
collections:
  posts:
    output: true
    permalink: '/posts/:title/'

defaults:
  -
    scope:
      type: posts
    values:
      _options:
        file_path: # Front matter field
          uploads_dir: "assets/images/posts/"

# Cloudcannon Options

_options:
  main_image_path:
    width: 284
    height: 283
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: false
  share_image_path:
    width: 1200
    height: 1200
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: false
    uploads_dir: "assets/images/share"
_comments:
  share_image_path: "The social share image needs to be at least 1200x1200px and if not that exact same size CloudCannon will scale and crop it to 1200x1200."

# Google Analytics 
google_analytics_tracking_id: 'UA-80029-52'

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "README.md",
  "assets/**/*.md", # Don't want assets/sass/partials/README.md and potentially other *.md
  "gulpfile.js",
  "node_modules",
  "npm-shrinkwrap.json",
  "package-lock.json",
  "package.json",
  "proofScripts.js",

  # Development files not wanted in production site
  # Notes:
  # * `*.map` files aren't of value because we aren't including `*.scss` or `assets/js/dev/*`
  # * May wish to comment these exclusions during develpment because they are useful for debugging.
  "*.map",
  "*.scss",
  "assets/js/dev"
  ]
