#We have struggled getting appveyor to install all devDependencies.
#* Appveyor really only needs a subset of the dependencies, so we are
#  only installing `production` dependencies and manually installing
#  just the packages needed to run `npm test`
#* Useful reference: https://www.appveyor.com/docs/lang/nodejs-iojs/
#
# node-gyp requires VS 2015 or greater. So using 2017. (Have tried 2015 and had same results)
# * `npm config set msvs_version 2015`
# * `npm install -g node-gyp`
# Current error:
# LINK : fatal error LNK1104: cannot open file 'C:\Users\appveyor\.node-gyp\6.12.1\Debug\node.lib' [C:\projects\optirtc-com\node_modules\uws\build\uws.vcxproj]
# It has to do with package `uws` which is required by socket.io which is required by browser-sync
image:
- Visual Studio 2017

environment:
    NODE_GYP_DIR: '%USERPROFILE%\.node-gyp'
    nodejs_version: "6.12.1"
    npm_version: "3.10.10"
    priv_key:
        secure: LiV6E1dSaRBLUyOWXvX/46ta/1fiUfNAMBIu46K4QIIpncInve60TtABtCEQW+u8fORmku5lp+Li7C/mr/XkEWCajdIEhH8JlxKhrYzDIcLQgD8yBiYQOewPYZNA2dOr+ezhKYVqyX/idhFDdDnqzp8caJDcgEqXnoym7rfpzd7Q8tpAtEc+y7mStWAsa3+2ExIlmxrINULOvcSwWwO962CpoXs6WE6NzXX6lkLyPfke9+FGsjeX7pQy+spMhpTRxz8GdtB0rECQoPkTnl21nog4VMd3f9tXNunOtGVz2TT/+5JuhbiZt+Go/EVo09qBwnU4S7k14/8oLO1ytq6vEizguzUkYv82lZ7wyF+em6ktaqIa3JZ3P6R4C5CnQ+BzmiHVypPoX9N7m6g1MtlhvVj1k/cZWN8/OpJ+qvRtrBEMXxWllL39WxVJk8t/XmIAnM9KpqMV2LvQIaIHVwT28YAkCo3DOW2Adf/Ecd1mTuBKINRo9lfIYmAuA3Ir1Q0U0ivgqX9uJt3iGGkws+NnlQ5CaLPIRCOG8B0Da/7yuMxWLX+3dIe1VXYQRXPMnRYJcnDhi2A2pGHPTL0WOhBuUZZdSMRNCbGmwhLPoOT+sBLxPdqGJV/Aor/KKBmgWNCQhp6z6I+fkEdEq4b/Be3BhLL0eTHV++qpFHEsRL05u97Gf5tqa0QvSPAAwUITEOz9C6tp4Q4887bVgvUaBXpli1n+sl9ZAOSl51OssVT5pF53rUkWNhGJ2C1t42jzJBEEnPtDy556+lNnEq5lTh4DF7V39k/BWrob751EbsB3+d3PH+d94F+rr5gY4leyVG46YEYfSe17kunqLz3QzM7qHKatky1US+Y4aL1lY8UFAf5TqtoOUoX6uk33C/WccuQxwpfW9XeZGI8y0pXEVnWjnTabSASD+h1ByMGcSXYOqtCvEvTmaj42sQ8GVc8WEGdgvr807HEw2A3F/C33waMqULXgvwW807JAMIlMgw830qqgUEBo6/yytlY6agwM6bRW4IuV5EbXWRJuv/YHwPb19fwxra0cf+KtfaOni8JIU/0KvYPas31mEv3f8oQE29XjHaB8s9gWvpUsI5Rh7v7x/ULA3hinulioIeVVS4KYkvoL5YlUwE2Sr2AWzPfhX7e6zFQbx+jrQBgmRV+awv85Vn25FQ3hSQ3FJqel0/SJ8bLH5CxON1yILdhp33mIJV14D0JhtvUxSFzttnpmcXp8Q8Hh7gfzriEtpMGVz7y4gern378PXlUSOjRggxCAk/WZ2yUqnH6OVQmywInBpA6USH0eI71Bbius0C64R/tyV57xDM4iMd7D5QDXuEuB5oHMAmiibv0dm9Uf8Wk6OQ9IWGyWjEee6ibpJRZfd/AOjOekWiSBjA2pKgGO4NpHpj6VbSsXZe9lsbNBKQf2sRfO0XpFR/dtKSJGs9lLnh8vrq3bRMSctHImrEXF7v4JSGDQ31ywSr6HKmUZdPn24gVNEupJcaqdGE+pdUwLxbBBZe4w8UjfZ+xnqpGyXoOSIGEqtKFZ/NzT81UfOCrQvmA456iyF5hu3DuqhjTABRZH58RhPzBInxSqCU4uMFT8ecDD/YAsigDzjuEDsnmkBN6zEKewNAW8J5vqrxkPjfSw5izfGJ+PmtSa0IkG+WS004MvCWpUWGplVrh6Es8Bl80KuzaKiYYJoZbTSlSZYslSfiZJEeS9rK3xQ9ThUEucnBSgyDt3pkAtA+AHdfSXJZv9nUrZ7EgE2Z0vWZwnlLzf0AKQE/WDH9aGl7RIylKhkMP4QtIrdt1GhXz3QEVg8WHMPa72GS8BZq1C9bL5skvQoySSAIfhndxyiORXrOBHag4+OsaRJofRVH3Vi5iVn/IqRJ2IoJVBZrypVbNLAvmSn4h7nFC4GoWBCw6DtesxayZhJFJDn5zIQnUo8koc8rMc+dgAmuj7xFzBK4R/7hy5K7U4cZBljzzsDVZj3lbkevEGYs3PcjOC9vAZ3ouYLd4lSvn2A+iDcbMNk2eIRNxP8VyMhZLd48DcY+AwogXkI0qNRP2JB7rdjzphf+V9erjFFXe5fa0DcbCmqoyfR/8WzXm2SvaA5X2DOQzFrapQLi6AUXYjiOc71/i5xCV9usvuWi63/NoExZKfQ1dkwQcbEQHqXEgMRVoiwA+I2RsFBisu

branches:
    except:
        - /^.*WIP$/

install:
    - echo "userprofile = %userprofile%"
    - echo "HOME = %HOME%"
    - ps: Install-Product node $env:nodejs_version
    - echo "npm install -g npm@%npm_version%"
    - npm install -g npm@%npm_version%
    - set PATH=%APPDATA%\npm;%PATH%
    # - npm config set msvs_version 2015
    # - npm install -g node-gyp
    - echo "%PATH%"
    # - node-gyp -v
    - npm install --only=production
    - npm install eslint
    # In future, if we want to run `npm run build`, we'll need to write a gulp script
    # that does not depend on dev-dependencies that cause appveyor to choke on npm install
    # Today we don't need this because we are committing the built static js and css etc.

test_script:
    - node --version
    - npm --version
    - echo PATH=%PATH%
    - echo PATHEXT=%PATHEXT%
    - npm test

# There is no build to perform before testing. Build of static content is committed to git repto git repo
# In future, we may wish to have a custom build_script... But this script does not need MSBuild tools.
build: off

# See: https://www.appveyor.com/docs/build-cache/
# Notes:
# * Caching:
#   * global npm cache
#   * local npm cache
# * Caches depend on appveyor.yml. So if appveyor.yml changes, these caches are invalid
#   and will not be used.
cache:
    - '%APPDATA%\npm-cache -> appveyor.yml'
    - 'node_modules -> package.json'
    - 'package.json -> appveyor.yml'
